using System.Globalization;
using CommunityToolkit.Maui.Core;
using CommunityToolkit.Maui.Views;
using Microsoft.Extensions.Logging;
using MusicSalesApp.Maui.ViewModels;

namespace MusicSalesApp.Maui.Views;

public partial class MusicLibraryPage : ContentPage
{
    private readonly MusicLibraryViewModel _viewModel;
    private readonly ILogger<MusicLibraryPage> _logger;

    public MusicLibraryPage(MusicLibraryViewModel viewModel, ILogger<MusicLibraryPage> logger)
    {
        _viewModel = viewModel;
        _logger = logger;
        BindingContext = viewModel;

        // Subscribe to ViewModel property changes to sync MediaElement with playback state
        _viewModel.PropertyChanged += OnViewModelPropertyChanged;

        // Add converter to page resources before InitializeComponent
        Resources.Add("PlayPauseGlyphConverter", new PlayPauseGlyphConverter());

        InitializeComponent();

        // Wire RefreshView command in code-behind to avoid MAUIG2045
        // (MAUI XAML source gen can't see commands generated by CommunityToolkit.Mvvm)
        SongsRefreshView.Command = _viewModel.LoadSongsCommand;

        // Subscribe to MediaElement events for diagnostics
        AudioPlayer.StateChanged += OnMediaStateChanged;
        AudioPlayer.MediaOpened += OnMediaOpened;
        AudioPlayer.MediaFailed += OnMediaFailed;
        AudioPlayer.MediaEnded += OnMediaEnded;

        _logger.LogInformation("[Audio] MusicLibraryPage constructed. ShouldAutoPlay={ShouldAutoPlay}", AudioPlayer.ShouldAutoPlay);
    }

    protected override async void OnAppearing()
    {
        base.OnAppearing();

        if (_viewModel.Songs.Count == 0)
        {
            await _viewModel.LoadSongsCommand.ExecuteAsync(null);
        }
    }

    protected override void OnDisappearing()
    {
        base.OnDisappearing();
        AudioPlayer.Stop();
    }

    private void OnViewModelPropertyChanged(object? sender, System.ComponentModel.PropertyChangedEventArgs e)
    {
        switch (e.PropertyName)
        {
            case nameof(MusicLibraryViewModel.CurrentlyPlayingSong):
                HandleSongChanged();
                break;
            case nameof(MusicLibraryViewModel.IsPlaying):
                HandlePlayStateChanged();
                break;
        }
    }

    private void HandleSongChanged()
    {
        var song = _viewModel.CurrentlyPlayingSong;
        if (song == null)
        {
            _logger.LogInformation("[Audio] HandleSongChanged: song is null, stopping.");
            AudioPlayer.Stop();
            AudioPlayer.Source = null;
            return;
        }

        _logger.LogInformation("[Audio] HandleSongChanged: Title={Title}, StreamUrl={StreamUrl}",
            song.SongTitle, song.StreamUrl ?? "(null)");

        if (!string.IsNullOrEmpty(song.StreamUrl))
        {
            // Stop current playback before switching source.
            // ShouldAutoPlay="True" will start playback once the new source is loaded.
            AudioPlayer.Stop();
            var source = MediaSource.FromUri(song.StreamUrl);
            _logger.LogInformation("[Audio] Setting MediaSource: Type={SourceType}", source?.GetType().Name);
            AudioPlayer.Source = source;
            _logger.LogInformation("[Audio] Source set. CurrentState={State}, Volume={Volume}",
                AudioPlayer.CurrentState, AudioPlayer.Volume);
        }
        else
        {
            _logger.LogWarning("[Audio] HandleSongChanged: StreamUrl is null/empty, skipping.");
        }
    }

    private void HandlePlayStateChanged()
    {
        _logger.LogInformation("[Audio] HandlePlayStateChanged: IsPlaying={IsPlaying}, CurrentState={State}, Song={Song}",
            _viewModel.IsPlaying, AudioPlayer.CurrentState, _viewModel.CurrentlyPlayingSong?.SongTitle ?? "(null)");

        if (_viewModel.CurrentlyPlayingSong == null) return;

        // Only pause/resume — source changes are handled by HandleSongChanged + ShouldAutoPlay
        if (_viewModel.IsPlaying)
        {
            if (AudioPlayer.CurrentState == MediaElementState.Paused)
            {
                _logger.LogInformation("[Audio] Resuming from paused state.");
                AudioPlayer.Play();
            }
            else
            {
                _logger.LogInformation("[Audio] IsPlaying=true but CurrentState={State}, not calling Play (ShouldAutoPlay handles it).",
                    AudioPlayer.CurrentState);
            }
        }
        else
        {
            _logger.LogInformation("[Audio] Pausing.");
            AudioPlayer.Pause();
        }
    }

    // --- MediaElement event handlers for diagnostics ---

    private void OnMediaStateChanged(object? sender, MediaStateChangedEventArgs e)
    {
        _logger.LogInformation("[Audio] StateChanged: {Previous} -> {New}", e.PreviousState, e.NewState);
    }

    private void OnMediaOpened(object? sender, EventArgs e)
    {
        _logger.LogInformation("[Audio] MediaOpened! Duration={Duration}, Position={Position}, Volume={Volume}",
            AudioPlayer.Duration, AudioPlayer.Position, AudioPlayer.Volume);
    }

    private void OnMediaFailed(object? sender, MediaFailedEventArgs e)
    {
        _logger.LogError("[Audio] MediaFailed! Error: {Error}", e.ErrorMessage);
    }

    private void OnMediaEnded(object? sender, EventArgs e)
    {
        _logger.LogInformation("[Audio] MediaEnded.");
    }
}

/// <summary>
/// Converts bool IsPlaying to the appropriate play/pause Unicode glyph.
/// </summary>
public class PlayPauseGlyphConverter : IValueConverter
{
    public object? Convert(object? value, Type targetType, object? parameter, CultureInfo culture)
    {
        return value is true ? "\u23F8" : "\u25B6"; // ⏸ or ▶
    }

    public object? ConvertBack(object? value, Type targetType, object? parameter, CultureInfo culture)
    {
        throw new NotSupportedException();
    }
}
