using System.Globalization;
using CommunityToolkit.Maui.Core;
using CommunityToolkit.Maui.Views;
using Microsoft.Extensions.Logging;
using MusicSalesApp.Maui.ViewModels;

namespace MusicSalesApp.Maui.Views;

public partial class MusicLibraryPage : ContentPage
{
    private readonly MusicLibraryViewModel _viewModel;
    private readonly ILogger<MusicLibraryPage> _logger;
    private IDispatcherTimer? _progressTimer;
    private bool _isSeeking;

    public MusicLibraryPage(MusicLibraryViewModel viewModel, ILogger<MusicLibraryPage> logger)
    {
        _viewModel = viewModel;
        _logger = logger;
        BindingContext = viewModel;

        // Subscribe to ViewModel property changes to sync MediaElement with playback state
        _viewModel.PropertyChanged += OnViewModelPropertyChanged;

        // Add converters to page resources before InitializeComponent
        Resources.Add("PlayPauseGlyphConverter", new PlayPauseGlyphConverter());
        Resources.Add("DurationConverter", new DurationConverter());

        InitializeComponent();

        // Wire RefreshView command in code-behind to avoid MAUIG2045
        // (MAUI XAML source gen can't see commands generated by CommunityToolkit.Mvvm)
        SongsRefreshView.Command = _viewModel.LoadSongsCommand;

        // Subscribe to MediaElement events for diagnostics
        AudioPlayer.StateChanged += OnMediaStateChanged;
        AudioPlayer.MediaOpened += OnMediaOpened;
        AudioPlayer.MediaFailed += OnMediaFailed;
        AudioPlayer.MediaEnded += OnMediaEnded;

        // Wire up slider seek events
        ProgressSlider.DragStarted += OnSliderDragStarted;
        ProgressSlider.DragCompleted += OnSliderDragCompleted;

        _logger.LogInformation("[Audio] MusicLibraryPage constructed. ShouldAutoPlay={ShouldAutoPlay}", AudioPlayer.ShouldAutoPlay);
    }

    protected override async void OnAppearing()
    {
        base.OnAppearing();

        if (_viewModel.Songs.Count == 0)
        {
            await _viewModel.LoadSongsCommand.ExecuteAsync(null);
        }

        // Load stream qualifying threshold from the server
        await _viewModel.LoadStreamQualifyingSecondsAsync();

        // Start SignalR connections for real-time updates
        await _viewModel.StartSignalRAsync();
    }

    protected override void OnDisappearing()
    {
        base.OnDisappearing();
        StopProgressTimer();
        AudioPlayer.Stop();
    }

    // --- Progress timer ---

    private void StartProgressTimer()
    {
        if (_progressTimer != null) return;

        _progressTimer = Dispatcher.CreateTimer();
        _progressTimer.Interval = TimeSpan.FromMilliseconds(500);
        _progressTimer.Tick += OnProgressTimerTick;
        _progressTimer.Start();
    }

    private void StopProgressTimer()
    {
        if (_progressTimer == null) return;

        _progressTimer.Stop();
        _progressTimer.Tick -= OnProgressTimerTick;
        _progressTimer = null;
    }

    private void OnProgressTimerTick(object? sender, EventArgs e)
    {
        if (_isSeeking) return;

        _viewModel.UpdatePlaybackPosition(AudioPlayer.Position, AudioPlayer.Duration);

        // Update slider directly — XAML OneWay binding breaks after user drag
        ProgressSlider.Value = _viewModel.PlaybackProgress;
    }

    // --- Slider seek ---

    private void OnSliderDragStarted(object? sender, EventArgs e)
    {
        _isSeeking = true;
    }

    private void OnSliderDragCompleted(object? sender, EventArgs e)
    {
        _isSeeking = false;
        var seekPosition = _viewModel.GetSeekPosition(ProgressSlider.Value);
        AudioPlayer.SeekTo(seekPosition);
        _logger.LogInformation("[Audio] Seeked to {Position}", seekPosition);
    }

    // --- ViewModel property change handling ---

    private void OnViewModelPropertyChanged(object? sender, System.ComponentModel.PropertyChangedEventArgs e)
    {
        switch (e.PropertyName)
        {
            case nameof(MusicLibraryViewModel.CurrentlyPlayingSong):
                HandleSongChanged();
                break;
            case nameof(MusicLibraryViewModel.IsPlaying):
                HandlePlayStateChanged();
                break;
        }
    }

    private void HandleSongChanged()
    {
        var song = _viewModel.CurrentlyPlayingSong;
        if (song == null)
        {
            _logger.LogInformation("[Audio] HandleSongChanged: song is null, stopping.");
            StopProgressTimer();
            AudioPlayer.Stop();
            AudioPlayer.Source = null;
            return;
        }

        _logger.LogInformation("[Audio] HandleSongChanged: Title={Title}, StreamUrl={StreamUrl}",
            song.SongTitle, song.StreamUrl ?? "(null)");

        if (!string.IsNullOrEmpty(song.StreamUrl))
        {
            // Stop current playback before switching source.
            // ShouldAutoPlay="True" will start playback once the new source is loaded.
            AudioPlayer.Stop();
            var source = MediaSource.FromUri(song.StreamUrl);
            _logger.LogInformation("[Audio] Setting MediaSource: Type={SourceType}", source?.GetType().Name);
            AudioPlayer.Source = source;
            _logger.LogInformation("[Audio] Source set. CurrentState={State}, Volume={Volume}",
                AudioPlayer.CurrentState, AudioPlayer.Volume);
        }
        else
        {
            _logger.LogWarning("[Audio] HandleSongChanged: StreamUrl is null/empty, skipping.");
        }
    }

    private void HandlePlayStateChanged()
    {
        _logger.LogInformation("[Audio] HandlePlayStateChanged: IsPlaying={IsPlaying}, CurrentState={State}, Song={Song}",
            _viewModel.IsPlaying, AudioPlayer.CurrentState, _viewModel.CurrentlyPlayingSong?.SongTitle ?? "(null)");

        if (_viewModel.CurrentlyPlayingSong == null) return;

        // Only pause/resume — source changes are handled by HandleSongChanged + ShouldAutoPlay
        if (_viewModel.IsPlaying)
        {
            if (AudioPlayer.CurrentState == MediaElementState.Paused)
            {
                _logger.LogInformation("[Audio] Resuming from paused state.");
                AudioPlayer.Play();
            }
            else
            {
                _logger.LogInformation("[Audio] IsPlaying=true but CurrentState={State}, not calling Play (ShouldAutoPlay handles it).",
                    AudioPlayer.CurrentState);
            }
            StartProgressTimer();
        }
        else
        {
            _logger.LogInformation("[Audio] Pausing.");
            AudioPlayer.Pause();
            StopProgressTimer();
        }
    }

    // --- MediaElement event handlers for diagnostics ---

    private void OnMediaStateChanged(object? sender, MediaStateChangedEventArgs e)
    {
        _logger.LogInformation("[Audio] StateChanged: {Previous} -> {New}", e.PreviousState, e.NewState);

        // Start timer when media begins playing (e.g. via ShouldAutoPlay)
        if (e.NewState == MediaElementState.Playing && _viewModel.IsPlaying)
        {
            StartProgressTimer();
        }
    }

    private void OnMediaOpened(object? sender, EventArgs e)
    {
        _logger.LogInformation("[Audio] MediaOpened! Duration={Duration}, Position={Position}, Volume={Volume}",
            AudioPlayer.Duration, AudioPlayer.Position, AudioPlayer.Volume);

        // Update duration immediately when media opens
        _viewModel.UpdatePlaybackPosition(AudioPlayer.Position, AudioPlayer.Duration);
    }

    private void OnMediaFailed(object? sender, MediaFailedEventArgs e)
    {
        _logger.LogError("[Audio] MediaFailed! Error: {Error}", e.ErrorMessage);
    }

    private void OnMediaEnded(object? sender, EventArgs e)
    {
        _logger.LogInformation("[Audio] MediaEnded.");
        StopProgressTimer();
        _viewModel.IsPlaying = false;
    }
}

/// <summary>
/// Converts bool IsPlaying to the appropriate play/pause Unicode glyph.
/// </summary>
public class PlayPauseGlyphConverter : IValueConverter
{
    public object? Convert(object? value, Type targetType, object? parameter, CultureInfo culture)
    {
        return value is true ? "\u23F8" : "\u25B6"; // ⏸ or ▶
    }

    public object? ConvertBack(object? value, Type targetType, object? parameter, CultureInfo culture)
    {
        throw new NotSupportedException();
    }
}

/// <summary>
/// Converts a nullable double (seconds) to a formatted duration string (m:ss or h:mm:ss).
/// </summary>
public class DurationConverter : IValueConverter
{
    public object? Convert(object? value, Type targetType, object? parameter, CultureInfo culture)
    {
        if (value is double seconds && !double.IsNaN(seconds) && !double.IsInfinity(seconds) && seconds > 0)
        {
            var ts = TimeSpan.FromSeconds(seconds);
            return ts.TotalHours >= 1
                ? ts.ToString(@"h\:mm\:ss")
                : ts.ToString(@"m\:ss");
        }
        return "--:--";
    }

    public object? ConvertBack(object? value, Type targetType, object? parameter, CultureInfo culture)
    {
        throw new NotSupportedException();
    }
}
